//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketValidator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketValidator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TICKET ALREADY REDEEMED!.
        /// </summary>
        internal static string AlreadyRedeemed {
            get {
                return ResourceManager.GetString("AlreadyRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string CardType_Free {
            get {
                return ResourceManager.GetString("CardType_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string CardType_Normal {
            get {
                return ResourceManager.GetString("CardType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string CardType_Special {
            get {
                return ResourceManager.GetString("CardType_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string CardType_Unknown {
            get {
                return ResourceManager.GetString("CardType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string CardVersion_Offline {
            get {
                return ResourceManager.GetString("CardVersion_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Ticket.
        /// </summary>
        internal static string CardVersion_Online {
            get {
                return ResourceManager.GetString("CardVersion_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to service!.
        /// </summary>
        internal static string ConnectionError_Failed {
            get {
                return ResourceManager.GetString("ConnectionError_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout while connecting to service!.
        /// </summary>
        internal static string ConnectionError_Timeout {
            get {
                return ResourceManager.GetString("ConnectionError_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown connection error:.
        /// </summary>
        internal static string ConnectionError_Unknown {
            get {
                return ResourceManager.GetString("ConnectionError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to ticket service lost! Please select a new connection.
        ///Status:.
        /// </summary>
        internal static string ConnectionLost_Content {
            get {
                return ResourceManager.GetString("ConnectionLost_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        internal static string ConnectionLost_Title {
            get {
                return ResourceManager.GetString("ConnectionLost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to ticket service could not be established!.
        /// </summary>
        internal static string InitialConnectionFaild_Content {
            get {
                return ResourceManager.GetString("InitialConnectionFaild_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to service.
        /// </summary>
        internal static string InitialConnectionFaild_Title {
            get {
                return ResourceManager.GetString("InitialConnectionFaild_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        internal static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        internal static string Redeemed {
            get {
                return ResourceManager.GetString("Redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem ({0}).
        /// </summary>
        internal static string RedeemTime {
            get {
                return ResourceManager.GetString("RedeemTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected and ready....
        /// </summary>
        internal static string ServiceConnected {
            get {
                return ResourceManager.GetString("ServiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown code - Ticket not found!.
        /// </summary>
        internal static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
