//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tickets.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes ALL tickets!.
        /// </summary>
        internal static string ButtonClearTip {
            get {
                return ResourceManager.GetString("ButtonClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tickets.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all tickets back to &quot;not redeemed&quot;..
        /// </summary>
        internal static string ButtonResetTip {
            get {
                return ResourceManager.GetString("ButtonResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        internal static string FileFilterExtension {
            get {
                return ResourceManager.GetString("FileFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets File.
        /// </summary>
        internal static string FileFilterText {
            get {
                return ResourceManager.GetString("FileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Server - {0}.
        /// </summary>
        internal static string MainTitleFile {
            get {
                return ResourceManager.GetString("MainTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string RibbonButtonExit {
            get {
                return ResourceManager.GetString("RibbonButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        internal static string RibbonButtonImportCSV {
            get {
                return ResourceManager.GetString("RibbonButtonImportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonSettings {
            get {
                return ResourceManager.GetString("RibbonButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string RibbonGroupLanguage {
            get {
                return ResourceManager.GetString("RibbonGroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RibbonTabFilter {
            get {
                return ResourceManager.GetString("RibbonTabFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string RibbonTabImport {
            get {
                return ResourceManager.GetString("RibbonTabImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonTabSettings {
            get {
                return ResourceManager.GetString("RibbonTabSettings", resourceCulture);
            }
        }
    }
}
