//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string AllFilterName {
            get {
                return ResourceManager.GetString("AllFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tickets.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes ALL tickets!.
        /// </summary>
        internal static string ButtonClearTip {
            get {
                return ResourceManager.GetString("ButtonClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Import.
        /// </summary>
        internal static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tickets.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all tickets back to &quot;not redeemed&quot;..
        /// </summary>
        internal static string ButtonResetTip {
            get {
                return ResourceManager.GetString("ButtonResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does have a header row.
        /// </summary>
        internal static string CheckBoxHasHeader {
            get {
                return ResourceManager.GetString("CheckBoxHasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really close Ticket Server?.
        /// </summary>
        internal static string CloseWarningCaption {
            get {
                return ResourceManager.GetString("CloseWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep on running the server..
        /// </summary>
        internal static string CloseWarningNo {
            get {
                return ResourceManager.GetString("CloseWarningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close the Ticket Server?
        ///No tickets can be redeemed anymore if you close the application!.
        /// </summary>
        internal static string CloseWarningText {
            get {
                return ResourceManager.GetString("CloseWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, exit the application..
        /// </summary>
        internal static string CloseWarningYes {
            get {
                return ResourceManager.GetString("CloseWarningYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV-Files.
        /// </summary>
        internal static string CsvFilterName {
            get {
                return ResourceManager.GetString("CsvFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the ticket?.
        /// </summary>
        internal static string DeleteTicketCaption {
            get {
                return ResourceManager.GetString("DeleteTicketCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, do NOT delete the ticket..
        /// </summary>
        internal static string DeleteTicketNo {
            get {
                return ResourceManager.GetString("DeleteTicketNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the ticket?
        ///This will delete the ticket forever and without a way to restore it!.
        /// </summary>
        internal static string DeleteTicketText {
            get {
                return ResourceManager.GetString("DeleteTicketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete the ticket..
        /// </summary>
        internal static string DeleteTicketYes {
            get {
                return ResourceManager.GetString("DeleteTicketYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail.
        /// </summary>
        internal static string FieldMail {
            get {
                return ResourceManager.GetString("FieldMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string FieldPhone {
            get {
                return ResourceManager.GetString("FieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string FieldStreet {
            get {
                return ResourceManager.GetString("FieldStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string FieldZip {
            get {
                return ResourceManager.GetString("FieldZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        internal static string FileFilterExtension {
            get {
                return ResourceManager.GetString("FileFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets File.
        /// </summary>
        internal static string FileFilterText {
            get {
                return ResourceManager.GetString("FileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Mode.
        /// </summary>
        internal static string GroupTicketMode {
            get {
                return ResourceManager.GetString("GroupTicketMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Type.
        /// </summary>
        internal static string GroupTicketType {
            get {
                return ResourceManager.GetString("GroupTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the column mapping:.
        /// </summary>
        internal static string ImportColumnText {
            get {
                return ResourceManager.GetString("ImportColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file to import:.
        /// </summary>
        internal static string ImportDescriptionText {
            get {
                return ResourceManager.GetString("ImportDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing tickets.
        /// </summary>
        internal static string ImportingTickets {
            get {
                return ResourceManager.GetString("ImportingTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ticket {0}/{1}....
        /// </summary>
        internal static string ImportStatusImporting {
            get {
                return ResourceManager.GetString("ImportStatusImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file....
        /// </summary>
        internal static string ImportStatusReadingFile {
            get {
                return ResourceManager.GetString("ImportStatusReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready....
        /// </summary>
        internal static string ImportStatusReady {
            get {
                return ResourceManager.GetString("ImportStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of the tickets:.
        /// </summary>
        internal static string ImportTypeText {
            get {
                return ResourceManager.GetString("ImportTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string ItemFreeTicket {
            get {
                return ResourceManager.GetString("ItemFreeTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ItemNormalTicket {
            get {
                return ResourceManager.GetString("ItemNormalTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string ItemOfflineTicket {
            get {
                return ResourceManager.GetString("ItemOfflineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string ItemOnlineTicket {
            get {
                return ResourceManager.GetString("ItemOnlineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string ItemSpecialTicket {
            get {
                return ResourceManager.GetString("ItemSpecialTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MainStatusLoading {
            get {
                return ResourceManager.GetString("MainStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready....
        /// </summary>
        internal static string MainStatusReady {
            get {
                return ResourceManager.GetString("MainStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets (redeemed/total):.
        /// </summary>
        internal static string MainStatusTickets {
            get {
                return ResourceManager.GetString("MainStatusTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string MainStatusTicketsValue {
            get {
                return ResourceManager.GetString("MainStatusTicketsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Server - {0}.
        /// </summary>
        internal static string MainTitleFile {
            get {
                return ResourceManager.GetString("MainTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string RibbonButtonExit {
            get {
                return ResourceManager.GetString("RibbonButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        internal static string RibbonButtonImportCSV {
            get {
                return ResourceManager.GetString("RibbonButtonImportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonSettings {
            get {
                return ResourceManager.GetString("RibbonButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string RibbonGroupLanguage {
            get {
                return ResourceManager.GetString("RibbonGroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RibbonTabFilter {
            get {
                return ResourceManager.GetString("RibbonTabFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string RibbonTabImport {
            get {
                return ResourceManager.GetString("RibbonTabImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonTabSettings {
            get {
                return ResourceManager.GetString("RibbonTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string StatusClient {
            get {
                return ResourceManager.GetString("StatusClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string StatusTime {
            get {
                return ResourceManager.GetString("StatusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string TabDatabase {
            get {
                return ResourceManager.GetString("TabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TabStatus {
            get {
                return ResourceManager.GetString("TabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City-Column:.
        /// </summary>
        internal static string TextBlockCityColumn {
            get {
                return ResourceManager.GetString("TextBlockCityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-Column:.
        /// </summary>
        internal static string TextBlockCodeColumn {
            get {
                return ResourceManager.GetString("TextBlockCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string TextBlockFile {
            get {
                return ResourceManager.GetString("TextBlockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail-Column:.
        /// </summary>
        internal static string TextBlockMailColumn {
            get {
                return ResourceManager.GetString("TextBlockMailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-Column:.
        /// </summary>
        internal static string TextBlockNameColumn {
            get {
                return ResourceManager.GetString("TextBlockNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone-Column:.
        /// </summary>
        internal static string TextBlockPhoneColumn {
            get {
                return ResourceManager.GetString("TextBlockPhoneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        internal static string TextBlockPreview {
            get {
                return ResourceManager.GetString("TextBlockPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column-Separator:.
        /// </summary>
        internal static string TextBlockSeparator {
            get {
                return ResourceManager.GetString("TextBlockSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street-Column:.
        /// </summary>
        internal static string TextBlockStreetColumn {
            get {
                return ResourceManager.GetString("TextBlockStreetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Mode:.
        /// </summary>
        internal static string TextBlockTicketMode {
            get {
                return ResourceManager.GetString("TextBlockTicketMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Type:.
        /// </summary>
        internal static string TextBlockTicketType {
            get {
                return ResourceManager.GetString("TextBlockTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip-Column:.
        /// </summary>
        internal static string TextBlockZipColumn {
            get {
                return ResourceManager.GetString("TextBlockZipColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string TextCity {
            get {
                return ResourceManager.GetString("TextCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string TextCode {
            get {
                return ResourceManager.GetString("TextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string TextId {
            get {
                return ResourceManager.GetString("TextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        internal static string TextMail {
            get {
                return ResourceManager.GetString("TextMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Ticket:.
        /// </summary>
        internal static string TextOnline {
            get {
                return ResourceManager.GetString("TextOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string TextPhone {
            get {
                return ResourceManager.GetString("TextPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem date:.
        /// </summary>
        internal static string TextRedeemDate {
            get {
                return ResourceManager.GetString("TextRedeemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed:.
        /// </summary>
        internal static string TextRedeemed {
            get {
                return ResourceManager.GetString("TextRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        internal static string TextStreet {
            get {
                return ResourceManager.GetString("TextStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TextType {
            get {
                return ResourceManager.GetString("TextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip:.
        /// </summary>
        internal static string TextZip {
            get {
                return ResourceManager.GetString("TextZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TicketModeAll {
            get {
                return ResourceManager.GetString("TicketModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string TicketModeOffline {
            get {
                return ResourceManager.GetString("TicketModeOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string TicketModeOnline {
            get {
                return ResourceManager.GetString("TicketModeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TicketTypeAll {
            get {
                return ResourceManager.GetString("TicketTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string TicketTypeFree {
            get {
                return ResourceManager.GetString("TicketTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string TicketTypeNormal {
            get {
                return ResourceManager.GetString("TicketTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string TicketTypeSpecial {
            get {
                return ResourceManager.GetString("TicketTypeSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tickets.
        /// </summary>
        internal static string WindowImportTitle {
            get {
                return ResourceManager.GetString("WindowImportTitle", resourceCulture);
            }
        }
    }
}
