//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string AllFilterName {
            get {
                return ResourceManager.GetString("AllFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tickets.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes ALL tickets!.
        /// </summary>
        internal static string ButtonClearTip {
            get {
                return ResourceManager.GetString("ButtonClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Import.
        /// </summary>
        internal static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tickets.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all tickets back to &quot;not redeemed&quot;..
        /// </summary>
        internal static string ButtonResetTip {
            get {
                return ResourceManager.GetString("ButtonResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does have a header row.
        /// </summary>
        internal static string CheckBoxHasHeader {
            get {
                return ResourceManager.GetString("CheckBoxHasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV-Files.
        /// </summary>
        internal static string CsvFilterName {
            get {
                return ResourceManager.GetString("CsvFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string FieldCity {
            get {
                return ResourceManager.GetString("FieldCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string FieldCode {
            get {
                return ResourceManager.GetString("FieldCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail.
        /// </summary>
        internal static string FieldMail {
            get {
                return ResourceManager.GetString("FieldMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string FieldPhone {
            get {
                return ResourceManager.GetString("FieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string FieldStreet {
            get {
                return ResourceManager.GetString("FieldStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string FieldZip {
            get {
                return ResourceManager.GetString("FieldZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        internal static string FileFilterExtension {
            get {
                return ResourceManager.GetString("FileFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets File.
        /// </summary>
        internal static string FileFilterText {
            get {
                return ResourceManager.GetString("FileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the column mapping:.
        /// </summary>
        internal static string ImportColumnText {
            get {
                return ResourceManager.GetString("ImportColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file to import:.
        /// </summary>
        internal static string ImportDescriptionText {
            get {
                return ResourceManager.GetString("ImportDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ticket {0}/{1}....
        /// </summary>
        internal static string ImportStatusImporting {
            get {
                return ResourceManager.GetString("ImportStatusImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file....
        /// </summary>
        internal static string ImportStatusReadingFile {
            get {
                return ResourceManager.GetString("ImportStatusReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready....
        /// </summary>
        internal static string ImportStatusReady {
            get {
                return ResourceManager.GetString("ImportStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of the tickets:.
        /// </summary>
        internal static string ImportTypeText {
            get {
                return ResourceManager.GetString("ImportTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string ItemFreeTicket {
            get {
                return ResourceManager.GetString("ItemFreeTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ItemNormalTicket {
            get {
                return ResourceManager.GetString("ItemNormalTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string ItemOfflineTicket {
            get {
                return ResourceManager.GetString("ItemOfflineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string ItemOnlineTicket {
            get {
                return ResourceManager.GetString("ItemOnlineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string ItemSpecialTicket {
            get {
                return ResourceManager.GetString("ItemSpecialTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Server - {0}.
        /// </summary>
        internal static string MainTitleFile {
            get {
                return ResourceManager.GetString("MainTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string RibbonButtonExit {
            get {
                return ResourceManager.GetString("RibbonButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        internal static string RibbonButtonImportCSV {
            get {
                return ResourceManager.GetString("RibbonButtonImportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonSettings {
            get {
                return ResourceManager.GetString("RibbonButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string RibbonGroupLanguage {
            get {
                return ResourceManager.GetString("RibbonGroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RibbonTabFilter {
            get {
                return ResourceManager.GetString("RibbonTabFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string RibbonTabImport {
            get {
                return ResourceManager.GetString("RibbonTabImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonTabSettings {
            get {
                return ResourceManager.GetString("RibbonTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City-Column:.
        /// </summary>
        internal static string TextBlockCityColumn {
            get {
                return ResourceManager.GetString("TextBlockCityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-Column:.
        /// </summary>
        internal static string TextBlockCodeColumn {
            get {
                return ResourceManager.GetString("TextBlockCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string TextBlockFile {
            get {
                return ResourceManager.GetString("TextBlockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail-Column:.
        /// </summary>
        internal static string TextBlockMailColumn {
            get {
                return ResourceManager.GetString("TextBlockMailColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-Column:.
        /// </summary>
        internal static string TextBlockNameColumn {
            get {
                return ResourceManager.GetString("TextBlockNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone-Column:.
        /// </summary>
        internal static string TextBlockPhoneColumn {
            get {
                return ResourceManager.GetString("TextBlockPhoneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview:.
        /// </summary>
        internal static string TextBlockPreview {
            get {
                return ResourceManager.GetString("TextBlockPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column-Separator:.
        /// </summary>
        internal static string TextBlockSeparator {
            get {
                return ResourceManager.GetString("TextBlockSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street-Column:.
        /// </summary>
        internal static string TextBlockStreetColumn {
            get {
                return ResourceManager.GetString("TextBlockStreetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Mode:.
        /// </summary>
        internal static string TextBlockTicketMode {
            get {
                return ResourceManager.GetString("TextBlockTicketMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Type:.
        /// </summary>
        internal static string TextBlockTicketType {
            get {
                return ResourceManager.GetString("TextBlockTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip-Column:.
        /// </summary>
        internal static string TextBlockZipColumn {
            get {
                return ResourceManager.GetString("TextBlockZipColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tickets.
        /// </summary>
        internal static string WindowImportTitle {
            get {
                return ResourceManager.GetString("WindowImportTitle", resourceCulture);
            }
        }
    }
}
