//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketServer.Properties.SettingsWindow", typeof(SettingsWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test failed.
        /// </summary>
        internal static string FTPTestFaildCaption {
            get {
                return ResourceManager.GetString("FTPTestFaildCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test failed!.
        /// </summary>
        internal static string FTPTestFaildHeader {
            get {
                return ResourceManager.GetString("FTPTestFaildHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test sucessfull.
        /// </summary>
        internal static string FTPTestSuccessfullCaption {
            get {
                return ResourceManager.GetString("FTPTestSuccessfullCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Test sucessfull!.
        /// </summary>
        internal static string FTPTestSuccessfullHeader {
            get {
                return ResourceManager.GetString("FTPTestSuccessfullHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the FTP server could be established..
        /// </summary>
        internal static string FTPTestSuccessfullText {
            get {
                return ResourceManager.GetString("FTPTestSuccessfullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string groupBackup {
            get {
                return ResourceManager.GetString("groupBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION:.
        /// </summary>
        internal static string groupBackupAttention {
            get {
                return ResourceManager.GetString("groupBackupAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing files in the target location 
        ///will be overwritten!.
        /// </summary>
        internal static string groupBackupAttentionText {
            get {
                return ResourceManager.GetString("groupBackupAttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup to Folder.
        /// </summary>
        internal static string groupBackupFolder {
            get {
                return ResourceManager.GetString("groupBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup to FTP-Server.
        /// </summary>
        internal static string groupBackupFTP {
            get {
                return ResourceManager.GetString("groupBackupFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string groupBackupFTPTest {
            get {
                return ResourceManager.GetString("groupBackupFTPTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval:.
        /// </summary>
        internal static string groupBackupInterval {
            get {
                return ResourceManager.GetString("groupBackupInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string groupBackupMinutes {
            get {
                return ResourceManager.GetString("groupBackupMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string groupBackupPassword {
            get {
                return ResourceManager.GetString("groupBackupPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string groupBackupServer {
            get {
                return ResourceManager.GetString("groupBackupServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder:.
        /// </summary>
        internal static string groupBackupTargetFolder {
            get {
                return ResourceManager.GetString("groupBackupTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string groupBackupUser {
            get {
                return ResourceManager.GetString("groupBackupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Tickets.
        /// </summary>
        internal static string groupSpecialTickets {
            get {
                return ResourceManager.GetString("groupSpecialTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every ticket containing the string above in its 
        ///ticket-code will be declared as a special ticket.
        ///You can enter more then one by seperating
        ///them with semicolon (group1;group2;...)..
        /// </summary>
        internal static string groupSpecialTicketsFooter {
            get {
                return ResourceManager.GetString("groupSpecialTicketsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select a group of tickets which 
        ///will not be counted in any statistics.
        ///This can be used e.g. for employee tickets..
        /// </summary>
        internal static string groupSpecialTicketsHeader {
            get {
                return ResourceManager.GetString("groupSpecialTicketsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search-String:.
        /// </summary>
        internal static string groupSpecialTicketsString {
            get {
                return ResourceManager.GetString("groupSpecialTicketsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
