//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this source code is subject to the terms of the Microsoft end-user
// license agreement (EULA) under which you licensed this SOFTWARE PRODUCT.
// If you did not accept the terms of the EULA, you are not authorized to use
// this source code. For a copy of the EULA, please see the LICENSE.RTF on your
// install media.
//
//


import "oaidl.idl";
import "ocidl.idl";

const UINT CONFIG_DATA_PHONE_INFO_USERNAME            = 0x0001;
const UINT CONFIG_DATA_PHONE_INFO_AREACODES           = 0x0002;
const UINT CONFIG_DATA_PHONE_INFO_VOICEMAIL           = 0x0004;
const UINT CONFIG_DATA_PHONE_INFO_DIALOUTPREFIX       = 0x0008;
const UINT CONFIG_DATA_PHONE_SIP_URI                  = 0x0010;
const UINT CONFIG_DATA_PHONE_SIP_SERVER               = 0x0020;
const UINT CONFIG_DATA_PHONE_SIP_TRANSPORT            = 0x0040;
const UINT CONFIG_DATA_PHONE_SIP_AUTHTYPE             = 0x0080;
const UINT CONFIG_DATA_PHONE_SIP_ACCOUNT              = 0x0100;
const UINT CONFIG_DATA_EXCHANGE_OWASERVER             = 0x0200;
const UINT CONFIG_DATA_EXCHANGE_HTTPPROXY             = 0x0400;
const UINT CONFIG_DATA_PRESENCE_URI                   = 0x0800;
const UINT CONFIG_DATA_PRESENCE_SERVER                = 0x1000;
const UINT CONFIG_DATA_UPDATE_SMSSERVER               = 0x2000;

//OR'd together setting containing ALL above settings
const UINT CONFIG_DATA_ALL                            = 0x3FFF;

[
    object,
    uuid(39D6E331-EE5B-44bb-A7A9-DF462214B2EE),
    helpstring("IVoIPConfigurationDataStore Interface"),
    pointer_default(unique)
]
interface IVoIPConfigurationDataStore : IUnknown
{
    HRESULT Initialize();

    HRESULT Uninitialize();
    
    HRESULT WriteValue(
        UINT fWhichItem, 
        const WCHAR *c_wszNewValue
        );
        
    HRESULT ReadValue(
        UINT  fWhichItem, 
        WCHAR *wszDataBuffer, 
        UINT   cchDataBuffer
        );

    HRESULT UpdateSettingsFromXML(
        const WCHAR *c_wszXML, 
        UINT          fSettingsToUpdate, 
        UINT         *pfUpdatedSettings
        );
        
    HRESULT UpdateSettingsFromFile(
        const WCHAR *c_wszFileName,
        UINT          fSettingsToUpdate, 
        UINT         *pfUpdatedSettings
        );

    HRESULT UpdateSettingsFromServer(
        const WCHAR  *c_wszServerName,
        WCHAR*        ldap_cred,
        ULONG         ldap_method,
        UINT          fSettingsToUpdate, 
        UINT         *pfUpdatedSettings
        );
};

[
    uuid(52E736AF-4742-416d-80EC-87A1369C2C9E),
    version(1.0),
    helpstring("VoIPConfigurationDataStore Type Library")
]
library VOIPCONFIGURATIONDATASTORELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(CF8C9CD9-638E-40ff-8A51-8131EB8F496B),
        helpstring("VoIPConfigurationDataStore Class")
    ]
    coclass VoIPConfigurationDataStore
    {
        [default] interface IVoIPConfigurationDataStore;
    };

};

