//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tickets.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Status.
        /// </summary>
        internal static string ButtonClearStatus {
            get {
                return ResourceManager.GetString("ButtonClearStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes ALL tickets!.
        /// </summary>
        internal static string ButtonClearTip {
            get {
                return ResourceManager.GetString("ButtonClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tickets.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all tickets back to &quot;not redeemed&quot;..
        /// </summary>
        internal static string ButtonResetTip {
            get {
                return ResourceManager.GetString("ButtonResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors per unit.
        /// </summary>
        internal static string ChartStatisticSeriesPerUnit {
            get {
                return ResourceManager.GetString("ChartStatisticSeriesPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors.
        /// </summary>
        internal static string ChartStatisticSeriesTotal {
            get {
                return ResourceManager.GetString("ChartStatisticSeriesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        internal static string ChartStatisticTitle {
            get {
                return ResourceManager.GetString("ChartStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete tickets?.
        /// </summary>
        internal static string ClearDatabaseCaption {
            get {
                return ResourceManager.GetString("ClearDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, do NOT delete the tickets..
        /// </summary>
        internal static string ClearDatabaseNo {
            get {
                return ResourceManager.GetString("ClearDatabaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all tickets?
        ///This will delete the tickets forever and without a way to restore it!.
        /// </summary>
        internal static string ClearDatabaseText {
            get {
                return ResourceManager.GetString("ClearDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete the tickets..
        /// </summary>
        internal static string ClearDatabaseYes {
            get {
                return ResourceManager.GetString("ClearDatabaseYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really close Ticket Server?.
        /// </summary>
        internal static string CloseWarningCaption {
            get {
                return ResourceManager.GetString("CloseWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep on running the server..
        /// </summary>
        internal static string CloseWarningNo {
            get {
                return ResourceManager.GetString("CloseWarningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close the Ticket Server?
        ///No tickets can be redeemed anymore if you close the application!.
        /// </summary>
        internal static string CloseWarningText {
            get {
                return ResourceManager.GetString("CloseWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, exit the application..
        /// </summary>
        internal static string CloseWarningYes {
            get {
                return ResourceManager.GetString("CloseWarningYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string comboBoxResolution {
            get {
                return ResourceManager.GetString("comboBoxResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete the ticket?.
        /// </summary>
        internal static string DeleteTicketCaption {
            get {
                return ResourceManager.GetString("DeleteTicketCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, do NOT delete the ticket..
        /// </summary>
        internal static string DeleteTicketNo {
            get {
                return ResourceManager.GetString("DeleteTicketNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the ticket?
        ///This will delete the ticket forever and without a way to restore it!.
        /// </summary>
        internal static string DeleteTicketText {
            get {
                return ResourceManager.GetString("DeleteTicketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete the ticket..
        /// </summary>
        internal static string DeleteTicketYes {
            get {
                return ResourceManager.GetString("DeleteTicketYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tickets.
        /// </summary>
        internal static string FileFilterExtension {
            get {
                return ResourceManager.GetString("FileFilterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets File.
        /// </summary>
        internal static string FileFilterText {
            get {
                return ResourceManager.GetString("FileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Mode.
        /// </summary>
        internal static string GroupTicketMode {
            get {
                return ResourceManager.GetString("GroupTicketMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        internal static string GroupTicketRedeemed {
            get {
                return ResourceManager.GetString("GroupTicketRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket-Type.
        /// </summary>
        internal static string GroupTicketType {
            get {
                return ResourceManager.GetString("GroupTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MainStatusLoading {
            get {
                return ResourceManager.GetString("MainStatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready....
        /// </summary>
        internal static string MainStatusReady {
            get {
                return ResourceManager.GetString("MainStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets (redeemed/total):.
        /// </summary>
        internal static string MainStatusTickets {
            get {
                return ResourceManager.GetString("MainStatusTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string MainStatusTicketsValue {
            get {
                return ResourceManager.GetString("MainStatusTicketsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Server - {0}.
        /// </summary>
        internal static string MainTitleFile {
            get {
                return ResourceManager.GetString("MainTitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really reset tickets?.
        /// </summary>
        internal static string ResetDatabaseCaption {
            get {
                return ResourceManager.GetString("ResetDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, do NOT reset the tickets..
        /// </summary>
        internal static string ResetDatabaseNo {
            get {
                return ResourceManager.GetString("ResetDatabaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all tickets?
        ///This will reset the tickets without a way to restore the old state!.
        /// </summary>
        internal static string ResetDatabaseText {
            get {
                return ResourceManager.GetString("ResetDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, reset the tickets..
        /// </summary>
        internal static string ResetDatabaseYes {
            get {
                return ResourceManager.GetString("ResetDatabaseYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Minutes.
        /// </summary>
        internal static string Resolution15Minutes {
            get {
                return ResourceManager.GetString("Resolution15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        internal static string Resolution30Minutes {
            get {
                return ResourceManager.GetString("Resolution30Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Minutes.
        /// </summary>
        internal static string Resolution5Minutes {
            get {
                return ResourceManager.GetString("Resolution5Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        internal static string Resolution60Minutes {
            get {
                return ResourceManager.GetString("Resolution60Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string RibbonButtonExit {
            get {
                return ResourceManager.GetString("RibbonButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        internal static string RibbonButtonImportCSV {
            get {
                return ResourceManager.GetString("RibbonButtonImportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonSettings {
            get {
                return ResourceManager.GetString("RibbonButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string RibbonGroupLanguage {
            get {
                return ResourceManager.GetString("RibbonGroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RibbonTabFilter {
            get {
                return ResourceManager.GetString("RibbonTabFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string RibbonTabImport {
            get {
                return ResourceManager.GetString("RibbonTabImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonTabSettings {
            get {
                return ResourceManager.GetString("RibbonTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string StatusClient {
            get {
                return ResourceManager.GetString("StatusClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string StatusTime {
            get {
                return ResourceManager.GetString("StatusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string TabDatabase {
            get {
                return ResourceManager.GetString("TabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string TabStatistic {
            get {
                return ResourceManager.GetString("TabStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TabStatus {
            get {
                return ResourceManager.GetString("TabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TicketModeAll {
            get {
                return ResourceManager.GetString("TicketModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string TicketModeOffline {
            get {
                return ResourceManager.GetString("TicketModeOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string TicketModeOnline {
            get {
                return ResourceManager.GetString("TicketModeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TicketRedeemedAll {
            get {
                return ResourceManager.GetString("TicketRedeemedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TicketRedeemedNo {
            get {
                return ResourceManager.GetString("TicketRedeemedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeemed.
        /// </summary>
        internal static string TicketRedeemedYes {
            get {
                return ResourceManager.GetString("TicketRedeemedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TicketTypeAll {
            get {
                return ResourceManager.GetString("TicketTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string TicketTypeFree {
            get {
                return ResourceManager.GetString("TicketTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string TicketTypeNormal {
            get {
                return ResourceManager.GetString("TicketTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string TicketTypeSpecial {
            get {
                return ResourceManager.GetString("TicketTypeSpecial", resourceCulture);
            }
        }
    }
}
