//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5448.
// 
namespace TicketValidator.TicketServiceReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITicketService", Namespace="http://tempuri.org/")]
    public partial class TicketService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TicketService() {
            this.Url = "http://192.168.0.130:8880/tickets/ws";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITicketService/GetTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ticket GetTicket([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string code) {
            object[] results = this.Invoke("GetTicket", new object[] {
                        code});
            return ((Ticket)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTicket(string code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTicket", new object[] {
                        code}, callback, asyncState);
        }
        
        /// <remarks/>
        public Ticket EndGetTicket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Ticket)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITicketService/RedeemTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RedeemTicket(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out bool RedeemTicketResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool RedeemTicketResultSpecified) {
            object[] results = this.Invoke("RedeemTicket", new object[] {
                        id,
                        idSpecified});
            RedeemTicketResult = ((bool)(results[0]));
            RedeemTicketResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRedeemTicket(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RedeemTicket", new object[] {
                        id,
                        idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndRedeemTicket(System.IAsyncResult asyncResult, out bool RedeemTicketResult, out bool RedeemTicketResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            RedeemTicketResult = ((bool)(results[0]));
            RedeemTicketResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TicketService")]
    public partial class Ticket {
        
        private string addressField;
        
        private string cityField;
        
        private string codeField;
        
        private string eMailField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isOnlineTicketField;
        
        private bool isOnlineTicketFieldSpecified;
        
        private bool isRedeemedField;
        
        private bool isRedeemedFieldSpecified;
        
        private string nameField;
        
        private string phoneField;
        
        private System.DateTime redeemDateField;
        
        private bool redeemDateFieldSpecified;
        
        private CardType typeField;
        
        private bool typeFieldSpecified;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsOnlineTicket {
            get {
                return this.isOnlineTicketField;
            }
            set {
                this.isOnlineTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOnlineTicketSpecified {
            get {
                return this.isOnlineTicketFieldSpecified;
            }
            set {
                this.isOnlineTicketFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsRedeemed {
            get {
                return this.isRedeemedField;
            }
            set {
                this.isRedeemedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsRedeemedSpecified {
            get {
                return this.isRedeemedFieldSpecified;
            }
            set {
                this.isRedeemedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RedeemDate {
            get {
                return this.redeemDateField;
            }
            set {
                this.redeemDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RedeemDateSpecified {
            get {
                return this.redeemDateFieldSpecified;
            }
            set {
                this.redeemDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CardType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TicketService")]
    public enum CardType {
        
        /// <remarks/>
        Free,
        
        /// <remarks/>
        Normal,
    }
}
